SELECT API, SW_NAME, BU_ID, PROJECT, AZIMUTH, DOG_LEG, INCLINATION, MEAS_DEPTH, SUBSEA_DEPTH, TVD_DEPTH
FROM PUBLIC_PROJECT.DEV_SURVEY_HIST_DEPTH_TVD_VEW
WHERE BU_ID = 'MILNEPT'
AND SW_NAME LIKE :param